# Generated by Django 4.2.17 on 2026-04-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], help_text="'credit' for money in, 'debit' for money out", max_length=10)),
                ('amount_paise', models.BigIntegerField(help_text='Amount in paise (1/100 of a rupee). POSITIVE for credits, NEGATIVE for debits. e.g., ₹500.00 credit = +50000, ₹200.00 debit = -20000')),
                ('description', models.CharField(help_text='Human-readable description of this transaction', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(help_text='Which merchant this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
