# Generated by Django 4.2.17 on 2026-04-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(help_text='Client-provided UUID for idempotency')),
                ('response_body', models.JSONField(blank=True, help_text='Cached response to return for duplicate requests', null=True)),
                ('response_status_code', models.IntegerField(blank=True, help_text='HTTP status code of the cached response', null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this key expires and can be reused')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField(help_text='Payout amount in paise (always positive)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0, help_text="How many times we've tried to process this payout")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payout reached a terminal state (completed/failed)', null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merchants.bankaccount')),
                ('idempotency_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payouts.idempotencykey')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='payouts_pay_merchan_9a626f_idx'), models.Index(fields=['status', 'updated_at'], name='payouts_pay_status_fa602c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['expires_at'], name='payouts_ide_expires_f51cdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together={('merchant', 'key')},
        ),
    ]
