# Generated by Django 4.2.17 on 2026-04-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business or individual name', max_length=255)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Indian bank account number', max_length=20)),
                ('ifsc_code', models.CharField(help_text='IFSC code (11 characters, e.g., SBIN0001234)', max_length=11)),
                ('nickname', models.CharField(blank=True, default='', help_text="Friendly name like 'Business Account' or 'Savings'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text="Soft delete flag — inactive accounts can't receive payouts")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(help_text='The merchant who owns this bank account', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='merchants.merchant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
